
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - redis
      - auth-service
      - post-service
    volumes:
      - ./api-gateway/src:/app/src
      - ./api-gateway/protos:/app/protos
      - ./auth-service/src/grpc/generated:/app/src/grpc/generated
      - ./api-gateway/logs:/app/logs
    networks:
      - shared
    command: sh -c "npx ts-node src/generate.ts && npm run dev"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3001:3001"
      - "50051:50051"
    # depends_on:
    #   auth-db:
    #     condition: service_healthy
    env_file:
      - ./auth-service/.env
    volumes:
      - ./auth-service/src:/app/src
      - ./auth-service/protos:/app/protos
      - ./auth-service/src/grpc/generated:/app/src/grpc/generated
      - ./auth-service/prisma:/app/prisma
      - /app/node_modules
    networks:
      - shared
    # command: sh -c "npx ts-node src/generate.ts && npx prisma migrate deploy && npm run dev"
    command: sh -c "npx ts-node src/generate.ts && npx prisma db push && npm run dev"

  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    container_name: post-service
    # depends_on: 
    #   post-db:
    #     condition: service_healthy
    env_file:
      - ./post-service/.env
    volumes:
      - ./post-service/src:/app/src 
      - ./post-service/protos:/app/protos
      - ./post-service/src/grpc/generated:/app/src/grpc/generated
      - ./post-service/prisma:/app/prisma
      - /app/node_modules
    networks:
      - shared
    # dns: 8.8.8.8
    command: sh -c "npx ts-node src/generate.ts && npx prisma migrate deploy && npm run dev"
  
  # auth-db:
  #   image: postgres:alpine
  #   container_name: auth-db
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=devhuddle_auth
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   volumes:
  #     - auth_data:/var/lib/postgresql/data
  #   networks:
  #     - shared

  # post-db:
  #   # image: postgres:alpine
  #   image: postgres:13-alpine
  #   container_name: post-db
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=devhuddle_posts
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   volumes:
  #     - post_data:/var/lib/postgresql/data
  #   networks:
  #     - shared

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.4.0
  #   container_name: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   networks:
  #     - shared

  # kafka:
  #   image: confluentinc/cp-kafka:7.4.0
  #   container_name: kafka
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #     KAFKA_NUM_PARTITIONS: 3
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 1
  #   networks:
  #     - shared
  
  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka-ui
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - KAFKA_CLUSTERS_0_NAME=local
  #     - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
  #   depends_on:
  #     - kafka
  #   networks:
  #     - shared

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - shared

volumes:
  auth_data:
  redis_data:
  post_data:

networks:
  shared:
    driver: bridge
    